# Generated by Django 3.0.2 on 2020-12-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='', width_field=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
