# Generated by Django 3.0.2 on 2020-12-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0002_auto_20201224_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='face', width_field=200),
        ),
    ]
