# Generated by Django 3.0.2 on 2020-12-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0003_auto_20201224_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='face'),
        ),
    ]
