# Generated by Django 3.0.2 on 2020-12-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0004_auto_20201224_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prepaidId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
