# Generated by Django 3.0.2 on 2020-12-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0005_userprofile_prepaidid'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='medication',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
