# Generated by Django 3.0.2 on 2021-01-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0006_allergy_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
