# Generated by Django 3.0.2 on 2021-01-24 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0007_auto_20210118_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=3000)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qr_url',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='qrApp.QrURL'),
        ),
    ]
