# Generated by Django 3.0.2 on 2021-01-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0009_auto_20210124_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrurl',
            name='url',
            field=models.CharField(max_length=3000, unique=True),
        ),
    ]
