# Generated by Django 3.0.2 on 2021-01-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0010_auto_20210124_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='important_type_disease',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
