# Generated by Django 3.0.2 on 2021-02-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0012_auto_20210131_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='important_type_disease',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
