# Generated by Django 3.1.7 on 2021-04-05 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0014_userprofile_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pin',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Pin'),
        ),
    ]
